import type { Completion, Person, Task, Zone } from "@/lib/cleaning";

export const PEOPLE: Person[] = [
  { id: "lucy", label: "Lucy", emoji: "🦄", color: "lucy" },
  { id: "manu", label: "Manu", emoji: "🐱", color: "manu" },
];

export const ZONES: Zone[] = [
  {
    id: "cocina",
    label: "Cocina",
    tagline: "Comer bien sin declarar la encimera zona catastrófica.",
    sortOrder: 10,
  },
  { id: "gatos", label: "Gatos", tagline: "Ellos supervisan. Vosotros limpiáis.", sortOrder: 20 },
  {
    id: "habitacion",
    label: "Habitación",
    tagline: "Sábanas limpias: lujo doméstico de primer nivel.",
    sortOrder: 30,
  },
  {
    id: "ropa",
    label: "Ropa",
    tagline: "Que el cesto no desarrolle conciencia propia.",
    sortOrder: 40,
  },
  {
    id: "general",
    label: "General",
    tagline: "Pequeños gestos para que toda la casa respire mejor.",
    sortOrder: 50,
  },
];

export const TASKS: Task[] = [
  {
    id: "cocina_comida",
    zoneId: "cocina",
    name: "Hacer la comida",
    detail: "El turno alterna cada día; comida y cena siempre quedan repartidas.",
    schedule: {
      type: "daily",
      anchorDate: "2026-08-08",
      firstAssignee: "manu",
      preferredPeriod: "lunch",
    },
    sortOrder: 10,
    points: 1,
  },
  {
    id: "cocina_cena",
    zoneId: "cocina",
    name: "Hacer la cena",
    detail: "El turno opuesto a la comida y alterno cada día.",
    schedule: {
      type: "daily",
      anchorDate: "2026-08-08",
      firstAssignee: "lucy",
      preferredPeriod: "evening",
    },
    sortOrder: 20,
    points: 1,
  },
  {
    id: "cocina_superficies",
    zoneId: "cocina",
    name: "Limpiar encimera y superficies",
    detail: "Tarea retirada: ahora forma parte de recoger la cocina después de cada comida.",
    schedule: { type: "on_demand" },
    sortOrder: 30,
    points: 0,
    archived: true,
  },
  {
    id: "cocina_recoger_comida",
    zoneId: "cocina",
    name: "Recoger y limpiar la cocina después de la comida",
    detail:
      "Se activa al marcar la comida y se asigna a la otra persona. Incluye limpiar encimera y superficies, guardar lo que haya quedado y dejar la cocina recogida. El lavavajillas va aparte.",
    schedule: {
      type: "linked",
      sourceTaskId: "cocina_comida",
      anchorDate: "2026-08-10",
    },
    sortOrder: 31,
    points: 1,
  },
  {
    id: "cocina_recoger_cena",
    zoneId: "cocina",
    name: "Recoger y limpiar la cocina después de la cena",
    detail:
      "Se activa al marcar la cena y se asigna a la otra persona. Incluye limpiar encimera y superficies, guardar lo que haya quedado y dejar la cocina recogida. El lavavajillas va aparte.",
    schedule: {
      type: "linked",
      sourceTaskId: "cocina_cena",
      anchorDate: "2026-08-10",
    },
    sortOrder: 32,
    points: 1,
  },
  {
    id: "cocina_suelo",
    zoneId: "cocina",
    name: "Fregar el suelo de la cocina",
    detail: "A demanda, pero al menos una vez por semana; el turno semanal alterna.",
    schedule: { type: "on_demand_weekly", anchorDate: "2026-08-03", firstAssignee: "lucy" },
    sortOrder: 40,
    points: 1,
  },
  {
    id: "cocina_desayuno",
    zoneId: "cocina",
    name: "Preparar el desayuno",
    detail: "Prepararlo cuando haga falta. Puede puntuar una vez al día.",
    schedule: { type: "on_demand" },
    sortOrder: 5,
    points: 1,
    maxScoredCompletionsPerPeriod: 1,
  },
  {
    id: "cocina_poner_lavavajillas",
    zoneId: "cocina",
    name: "Poner el lavavajillas",
    detail:
      "Llenarlo después de cocinar y ponerlo en marcha cuando esté listo. Puede puntuar hasta tres veces al día.",
    schedule: { type: "on_demand" },
    sortOrder: 45,
    points: 1,
    maxScoredCompletionsPerPeriod: 3,
  },
  {
    id: "cocina_lavavajillas",
    zoneId: "cocina",
    name: "Recoger el lavavajillas",
    detail: "Vaciarlo y dejar cada cosa en su sitio. Puede puntuar hasta tres veces al día.",
    schedule: { type: "on_demand" },
    sortOrder: 50,
    points: 1,
    maxScoredCompletionsPerPeriod: 3,
  },
  {
    id: "gatos_arenero",
    zoneId: "gatos",
    name: "Limpiar el arenero",
    detail: "Cada día, alternando; preferiblemente por la noche.",
    schedule: {
      type: "daily",
      anchorDate: "2026-08-07",
      firstAssignee: "lucy",
      preferredPeriod: "evening",
    },
    sortOrder: 60,
    points: 1,
  },
  {
    id: "gatos_llenar_agua",
    zoneId: "gatos",
    name: "Llenar de agua el bebedero",
    detail: "Cuando baje el nivel, agua fresca para el comité supervisor.",
    schedule: { type: "on_demand" },
    sortOrder: 65,
    points: 1,
  },
  {
    id: "gatos_llenar_comida",
    zoneId: "gatos",
    name: "Llenar la comida de los gatos",
    detail: "Reponerla cuando haga falta, antes de que llegue la protesta oficial.",
    schedule: { type: "on_demand" },
    sortOrder: 66,
    points: 1,
  },
  {
    id: "gatos_bebedero",
    zoneId: "gatos",
    name: "Limpiar el bebedero",
    detail: "Una vez por semana, alternando semanas.",
    schedule: { type: "weekly", anchorDate: "2026-08-03", firstAssignee: "lucy" },
    sortOrder: 70,
    points: 1,
  },
  {
    id: "gatos_rascador",
    zoneId: "gatos",
    name: "Quitar pelos del árbol rascador",
    detail: "Una vez por semana, alternando semanas.",
    schedule: { type: "weekly", anchorDate: "2026-08-03", firstAssignee: "manu" },
    sortOrder: 80,
    points: 1,
  },
  {
    id: "habitacion_hacer_cama",
    zoneId: "habitacion",
    name: "Hacer la cama",
    detail: "Dejarla recogida y lista para que la habitación empiece bien el día.",
    schedule: { type: "on_demand" },
    sortOrder: 85,
    points: 1,
  },
  {
    id: "habitacion_sabanas",
    zoneId: "habitacion",
    name: "Cambiar las sábanas",
    detail: "A demanda y sin límite. Disponible para cualquiera siempre que haga falta.",
    schedule: { type: "on_demand" },
    sortOrder: 90,
    points: 1,
    unlimitedScoring: true,
  },
  {
    id: "habitacion_toallas_almohadas",
    zoneId: "habitacion",
    name: "Cambiar toallas y fundas de almohada",
    detail: "Una sola tarea cada domingo: cambiar las toallas y las fundas de almohada.",
    schedule: {
      type: "weekly",
      anchorDate: "2026-08-03",
      firstAssignee: "manu",
      rotationGroup: "textiles",
      dueDay: "sunday",
    },
    sortOrder: 100,
    points: 1,
  },
  {
    id: "habitacion_toallas",
    zoneId: "habitacion",
    name: "Cambiar las toallas",
    detail: "Tarea retirada: ahora forma parte del cambio conjunto de textiles del domingo.",
    schedule: {
      type: "weekly",
      anchorDate: "2026-08-03",
      firstAssignee: "manu",
      rotationGroup: "textiles",
    },
    sortOrder: 101,
    points: 1,
    archived: true,
  },
  {
    id: "habitacion_almohadas",
    zoneId: "habitacion",
    name: "Cambiar las fundas de almohada",
    detail: "Tarea retirada: ahora forma parte del cambio conjunto de textiles del domingo.",
    schedule: {
      type: "weekly",
      anchorDate: "2026-08-03",
      firstAssignee: "manu",
      rotationGroup: "textiles",
    },
    sortOrder: 102,
    points: 1,
    archived: true,
  },
  {
    id: "ropa_lavadora_color",
    zoneId: "ropa",
    name: "Poner y tender la lavadora de color",
    detail: "Incluye poner la lavadora y tender la ropa cuando termine.",
    schedule: { type: "on_demand" },
    sortOrder: 120,
    points: 1,
  },
  {
    id: "ropa_lavadora_blanco",
    zoneId: "ropa",
    name: "Poner y tender la lavadora de blanco",
    detail: "Incluye poner la lavadora y tender la ropa blanca cuando termine.",
    schedule: { type: "on_demand" },
    sortOrder: 130,
    points: 1,
  },
  {
    id: "ropa_lavadora_trapos",
    zoneId: "ropa",
    name: "Poner y tender la lavadora de trapos",
    detail: "Incluye poner la lavadora y tender los trapos cuando termine.",
    schedule: { type: "on_demand" },
    sortOrder: 135,
    points: 1,
  },
  {
    id: "ropa_recoger_color",
    zoneId: "ropa",
    name: "Recoger y doblar la ropa de color",
    detail: "Se asigna a la otra persona, aunque cualquiera puede recogerla y doblarla.",
    schedule: { type: "linked", sourceTaskId: "ropa_lavadora_color" },
    sortOrder: 140,
    points: 1,
  },
  {
    id: "ropa_recoger_blanco",
    zoneId: "ropa",
    name: "Recoger y doblar la ropa de blanco",
    detail: "Se asigna a la otra persona, aunque cualquiera puede recogerla y doblarla.",
    schedule: { type: "linked", sourceTaskId: "ropa_lavadora_blanco" },
    sortOrder: 150,
    points: 1,
  },
  {
    id: "ropa_recoger_trapos",
    zoneId: "ropa",
    name: "Recoger y guardar los trapos",
    detail: "Se asigna a la otra persona, aunque cualquiera puede recogerlos y guardarlos.",
    schedule: { type: "linked", sourceTaskId: "ropa_lavadora_trapos" },
    sortOrder: 155,
    points: 1,
  },
  {
    id: "general_plumero",
    zoneId: "general",
    name: "Pasar el plumero",
    detail: "Cuando el polvo empiece a hacerse demasiado cómodo.",
    schedule: { type: "on_demand" },
    sortOrder: 160,
    points: 1,
  },
  {
    id: "general_robot_deposito",
    zoneId: "general",
    name: "Rellenar y limpiar el depósito del robot aspirador",
    detail: "Vaciar y limpiar el depósito, y dejarlo relleno para el siguiente ciclo.",
    schedule: { type: "on_demand" },
    sortOrder: 170,
    points: 1,
    maxScoredCompletionsPerPeriod: 1,
  },
  {
    id: "general_robot_limpieza_profunda",
    zoneId: "general",
    name: "Limpiar el robot aspirador y la base en profundidad",
    detail: "Retirar pelos y suciedad de los cepillos, ruedas, sensores, robot y base.",
    schedule: { type: "on_demand" },
    sortOrder: 180,
    points: 1,
    maxScoredCompletionsPerPeriod: 1,
  },
];

export const INITIAL_COMPLETIONS: Completion[] = [
  {
    id: "seed-gatos-bebedero-2026-08-07",
    taskId: "gatos_bebedero",
    personId: "lucy",
    completedAt: "2026-08-07T12:00:00+02:00",
    reportedPeriod: "esta semana",
  },
];
